# language: python
# notifications:
#   webhooks:
#     urls:
#       - "https://webhooks.gitter.im/e/24d207e7c060eea433dd"
#     on_success: change  # options: [always|never|change] default: always
#     on_failure: always  # options: [always|never|change] default: always
#     on_start: never     # options: [always|never|change] default: always
# python:
#   - "3.6"      # current default Python on Travis CI
#   - "3.7"
#   - "3.8"
#   - "3.8-dev"  # 3.8 development branch
#   - "nightly"  # nightly build
# before_install:
#   - python --version
#   - pip install -r requirements.txt
# install:
#   - pip install ".[test]" . # install package + test dependencies
# script: pytest --cov=./ --cov-report=xml # run tests
# after_success:
#   - codecov # submit coverage
#   # - bash <(curl -s https://codecov.io/bash)


language: generic

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

dist: trusty

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/mlearner
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4

matrix:
    include:
        - os: linux
          sudo: required
          python: 3.7
          env: LATEST="false" IMAGE="false" COVERAGE="false" NUMPY_VERSION="1.18.1" SCIPY_VERSION="1.4.1" SKLEARN_VERSION="0.22.2" JOBLIB_VERSION=0.13.2 PANDAS_VERSION="1.0.1" IMAGEIO_VERSION="2.5.0" SKIMAGE_VERSION="0.15.0" DLIB_VERSION="19.17.0" MINICONDA_PYTHON_VERSION=3.7
        - os: linux
          python: 3.7
          env: LATEST="true" IMAGE="false" COVERAGE="true" NOTEBOOKS="false" MINICONDA_PYTHON_VERSION=3.7
        - os: osx
          language: generic
          osx_image: xcode11.2
          env: TOXENV=py37

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
    - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get update; fi
    - source ci/.travis_install.sh

script:
    - bash ci/.travis_test.sh
    # - bash coverage run -m unittest discover

after_success:
    - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
      recipients:
          - jaisenberafel@gmail.com.com
    webhooks:
      urls:
        - https://webhooks.gitter.im/e/24d207e7c060eea433dd
      on_success: change  # options: [always|never|change] default: always
      on_failure: always  # options: [always|never|change] default: always
      on_start: never     # options: [always|never|change] default: always
    # on_success: always
    # on_failure: always
