# https://www.mkdocs.org/user-guide/deploying-your-docs/

site_name: mlearner
site_url: https://jaisenbe58r.github.io/MLearner/
site_author: Jaime Sendra Berenguer
site_description: A library consisting of useful tools and extensions for the day-to-day data science tasks.


repo_url: https://github.com/jaisenbe58r/MLearner
repo_name: GitHub
edit_uri: docs/sources/user_guide/


#include_search: true # not necessary for this theme
docs_dir: sources


theme:
    name: null
    custom_dir: 'custom_theme/'

markdown_extensions:
  - tables
  - fenced_code
  - mdx_math:
      enable_dollar_delimiter: True #for use of inline $..$
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js
extra_css:
  - cinder/css/base.css
  - cinder/css/bootstrap-custom.css
  - cinder/css/bootstrap-custom.min.css
  - cinder/css/cinder.css
  - cinder/css/font-awesome-4.0.3.css
  - cinder/css/highlight.css

copyright: Copyright &copy; 2020-2024 <a href="https://www.linkedin.com/in/jaisenbe">Jaime Sendra</a>
google_analytics: ['UA-163860068-1', 'jaisenbe58r.github.io/MLearner/']

nav:
- Home: index.md
- User Guide:
  - USER_GUIDE_INDEX.md
  - data:
    - user_guide/data/wine_data.md
  - preprocessing:
    - user_guide/preprocessing/MeanCenterer.md
    # - user_guide/preprocessing/minmax_scaling.md
  - utils:
    # - user_guide/utils/Counter.md

- API:
  - api_subpackages/mlearner.data.md
  - api_subpackages/mlearner.preprocessing.md
  # - api_subpackages/mlearner.utils.md

- Installation: installation.md
- About:
  - Release Notes: CHANGELOG.md
  - How To Contribute: CONTRIBUTING.md
  - Contributors: contributors.md
  - License: license.md
  - Citing mlearner: cite.md
  - Discuss: discuss.md
